-- ============================================================
--  Real Estate App — PostgreSQL DDL (Supabase)
--  Tables: Listing, Enquiry
--  Auth:    Clerk (user IDs stored in "createdBy")
--  Storage: Supabase Storage (image URLs in images[])
--  Maps:    LocationIQ (lat/lng stored in coordinates JSON)
--  Email:   Resend (triggered on new Enquiry insert)
-- ============================================================


-- ─────────────────────────────────────────────
-- TABLE 1: Listing
-- Stores all property listings created by agents/admins.
-- Images are stored as a text array of Supabase Storage URLs.
-- Coordinates are stored as JSON { lat: number, lng: number }
--   populated via LocationIQ geocoding on the frontend.
-- "createdBy" holds the Clerk user_id of the listing creator.
-- ─────────────────────────────────────────────

CREATE TABLE public."Listing" (
    id               BIGINT                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Location
    address          CHARACTER VARYING        NULL,
    coordinates      JSON                     NULL,         -- { "lat": 28.6139, "lng": 77.2090 }
    city             CHARACTER VARYING        NULL,

    -- Ownership / Auth
    "createdBy"      CHARACTER VARYING        NULL,         -- Clerk user_id (e.g. "user_2abc...")

    -- Listing status
    active           BOOLEAN                  NOT NULL DEFAULT FALSE,

    -- Classification
    "Property_type"  CHARACTER VARYING[]      NULL,         -- e.g. ARRAY['Apartment', 'Villa']
    "listingType"    CHARACTER VARYING        NULL,         -- 'sale' | 'rent'

    -- Property details
    "Floor_plan"     CHARACTER VARYING        NULL,
    bedroom          INTEGER                  NULL,
    bathroom         INTEGER                  NULL,
    "builtIn"        CHARACTER VARYING        NULL,         -- Year built, e.g. '2021'
    parking          INTEGER                  NULL,
    "lotSize"        NUMERIC                  NULL,         -- In sq ft or sq m
    area             NUMERIC                  NULL,         -- Carpet/built-up area
    price            NUMERIC                  NULL,
    hoa              NUMERIC                  NULL,         -- Homeowners Association fee (monthly)

    -- Content
    description      TEXT                     NULL,
    images           TEXT[]                   NULL,         -- Supabase Storage public URLs

    CONSTRAINT "Listing_pkey" PRIMARY KEY (id)
) TABLESPACE pg_default;


-- ─────────────────────────────────────────────
-- TABLE 2: Enquiry
-- Stores inquiries submitted via the "Send Inquiry" form
--   on the Property Detail page.
-- On insert, a Resend transactional email is triggered
--   (handled in the Next.js API route / server action).
-- listing_id is a FK → Listing(id).
-- ─────────────────────────────────────────────

CREATE TABLE public."Enquiry" (
    id           BIGINT                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Foreign key to the listing being enquired about
    listing_id   BIGINT                   NULL,

    -- Sender contact details (captured from the inquiry form)
    name         CHARACTER VARYING        NULL,
    email        CHARACTER VARYING        NULL,
    phone        CHARACTER VARYING        NULL,
    message      TEXT                     NULL,

    CONSTRAINT enquiry_pkey            PRIMARY KEY (id),
    CONSTRAINT "Enquiry_listing_id_fkey"
        FOREIGN KEY (listing_id)
        REFERENCES public."Listing" (id)
) TABLESPACE pg_default;


-- ─────────────────────────────────────────────
-- RECOMMENDED INDEXES
-- (Add these after table creation for better query performance)
-- ─────────────────────────────────────────────

-- Speed up filtering active listings by city
CREATE INDEX IF NOT EXISTS idx_listing_city
    ON public."Listing" (city);

CREATE INDEX IF NOT EXISTS idx_listing_active
    ON public."Listing" (active);

-- Speed up fetching enquiries for a specific listing
CREATE INDEX IF NOT EXISTS idx_enquiry_listing_id
    ON public."Enquiry" (listing_id);

-- Speed up fetching listings by the agent who created them
CREATE INDEX IF NOT EXISTS idx_listing_created_by
    ON public."Listing" ("createdBy");


-- ─────────────────────────────────────────────
-- RELATIONSHIP SUMMARY
-- ─────────────────────────────────────────────
--
--  Listing (1) ──────────────── (Many) Enquiry
--    id  <────────────────────  listing_id  (FK)
--
--  One property listing can receive many enquiries.
--  Each enquiry belongs to exactly one listing.
--
-- ─────────────────────────────────────────────
-- EXTERNAL SERVICE MAPPING
-- ─────────────────────────────────────────────
--
--  Clerk Auth   → Listing."createdBy"  stores Clerk user_id string
--  Supabase     → Listing.images[]     stores public Storage bucket URLs
--  LocationIQ   → Listing.coordinates stores { lat, lng } JSON from geocoding API
--  Resend Email → Enquiry insert       triggers transactional email to agent
--
-- ============================================================